# Generated by Django 4.0.3 on 2022-03-19 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'default_related_name': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.folder')),
            ],
            options={
                'default_related_name': 'folders',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_descriptor', models.CharField(max_length=255, unique=True)),
                ('long_descriptor', models.TextField()),
            ],
            options={
                'default_related_name': 'topics',
            },
        ),
        migrations.CreateModel(
            name='FolderTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.folder')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.topic')),
            ],
            options={
                'default_related_name': 'folder_topics',
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='topics',
            field=models.ManyToManyField(through='v1.FolderTopic', to='v1.topic'),
        ),
        migrations.CreateModel(
            name='DocumentTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.document')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.topic')),
            ],
            options={
                'default_related_name': 'document_topics',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(through='v1.DocumentTopic', to='v1.topic'),
        ),
    ]
