version: '3.6'
services:
  spekit:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    volumes:
      - "./src:/src"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  caddy:
    build: ./Caddy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - "spekit"
    restart: always

volumes:
  db_data:
