version: '3.6'
services:
  spekit:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    volumes:
      - "./src:/src"
    command: >
      sh -c "python manage.py migrate"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_data:
